### ISSUE TITLE
encrypt all network traffic 

### ISSUE THREAD

**Issue by wesley-dean-gsa** [IMLS/estimating-wifi#137]
### User / Persona

security engineer

### Request

all network traffic needs to be encrypted

### Reason / Justification

comply with OMB M-22-09 (ZTA)

### Definition of Done (DoD)

- [ ] HTTPS / TLS is used for network HTTP traffic
- [ ] port 80 (HTTP) should only be used to redirect connections to HTTPS / TLS on port 443
- [ ] as HTTPS / TLS requires server-side certificates and keys, some mechanism will be required to generate, sign, and update the certificates (e.g., LetsEncrypt); setting this up will likely be a separate issue

### Acceptance Criteria (AC)

- [ ] unencrypted HTTP requests sent in plaintext on port 80 are redirected to HTTPS on port 443
- [ ] HTTPS / TLS certificates (fullchain) may be validated

### Other Notes

* OMB M-22-09: https://www.whitehouse.gov/wp-content/uploads/2022/01/M-22-09.pdf
