### ISSUE TITLE
Draft an ADR for the data model

### ISSUE THREAD

**Issue by meenubhooshanan** [IMLS/estimating-wifi#47]
**Background**

For phase 3.5, the team wanted to change the data model used in phase 3 to accommodate scaling in GA.

It covers the following stories:
#33 

**We'll know we're done when...**
- [ ] When a user can refer to it on our public Github repository to understand why we selected the data model.
  
**Tasks**
- [ ] Write the ADR

**Definition of Done**

- [ ] An Architectural Decision Record (ADR) has been drafted, reviewed, and approved for the selected data model.
