### ISSUE TITLE
Write DB queries for the front-end data visualization

### ISSUE THREAD

**Issue by meenubhooshanan** [IMLS/estimating-wifi#60]
**Background**

We need to query the `imlswifi.presences` table using `HTTP GET` requests to return results for data visualization on the front-end.

It covers the following stories:

#33 

**We'll know we're done when...**
- [ ] When a user can view all devices present during a 24-hour day (of their choosing)
  
**Tasks**
- [ ] Identify and prioritize visualizations we want to represent
- [ ] Write SQL queries that pull the fields needed from the DB for the prioritized visualizations
- [ ] Write HTTP GET requests based on the SQL queries

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by meenubhooshanan** [comment]
Visualizations to prioritize:
1. "All devices present during a 24 hour window"
2. "Sensor grouping"

Fields needed from `imlswifi.presences` table:
1. sensor_id, fscs_id, start_time, and end_time
2. All the unique/different sensor_ids with the same fscs_id

**Comment by meenubhooshanan** [comment]
Tabling (for now): averages, sensor grouping, open/closed hours, integrating w/ IMLS dataset
